### PR TITLE
use only overlays

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/elyra-aidevsecops-tutorial/issues/126

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Remove dependencies from root directory and move them to overlays to be compliant with best practices.

### CODE REVIEW

**Comment by pacospace** [comment]
@harshad16 @goern what is missing to merge?

**Comment by goern** [comment]
hmm, ja, strange

**Comment by harshad16** [comment]
This is the reason https://github.com/thoth-station/thoth-application/blob/8f81a96f370781bcf56bf2ed8f6492e3eeaeeba3/prow/overlays/cnv-prod/config.yaml#L273

as we have moved to overlay build here, we cant have build-check for this repo.
will remove that rule from prow, so that it can merge the pr in future.

**Comment by pacospace** [comment]
> This is the reason https://github.com/thoth-station/thoth-application/blob/8f81a96f370781bcf56bf2ed8f6492e3eeaeeba3/prow/overlays/cnv-prod/config.yaml#L273
> 
> as we have moved to overlay build here, we cant have build-check for this repo.
> will remove that rule from prow, so that it can merge the pr in future.

Thanks @harshad16 💯

**Pull request merged**
