### PR TITLE
Use smart changelog

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

### CODE REVIEW

**Comment by pacospace** [comment]
>  
> 
> Maybe we should turn it on by default on ebechet side.

sounds nice indeed, do you want to open feature request in Kebechet? @fridex

**Comment by fridex** [comment]
> > Maybe we should turn it on by default on ebechet side.
> 
> sounds nice indeed, do you want to open feature request in Kebechet? @fridex

Looks like we should have it already if anything does not override the default parameter:

https://github.com/thoth-station/kebechet/commit/2f9af40a56ac421ddded27ba9387732e29603260

**Comment by pacospace** [comment]
> > > Maybe we should turn it on by default on ebechet side.
> > 
> > 
> > sounds nice indeed, do you want to open feature request in Kebechet? @fridex
> 
> Looks like we should have it already if anything does not override the default parameter:
> 
> [thoth-station/kebechet@2f9af40](https://github.com/thoth-station/kebechet/commit/2f9af40a56ac421ddded27ba9387732e29603260)

Great then, Thanks for looking into it!

**Pull request merged**
