### PR TITLE
add more metrics

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

### CODE REVIEW

**Comment by harshad16** [comment]
{"average_latency": 0.04068811698816717, "average_error": 0.0}

**Comment by harshad16** [comment]
| metric_name     |     value |
|:----------------|----------:|
| average_latency | 0.0403881 |
| average_error   | 0         |

**Comment by harshad16** [comment]
Kebechet gathered metrics on your deployed model:

| metric_name     |     value |
|:----------------|----------:|
| average_latency | 0.0407731 |
| average_error   | 0         |

**Comment by harshad16** [comment]
The following table show gathered metrics on your deployed model.

| metric_name     |     value |
|:----------------|----------:|
| average_latency | 0.0403472 |
| average_error   | 0         |

**Comment by harshad16** [comment]
The following table shows gathered metrics on your deployed model.

| metric_name     |     value |
|:----------------|----------:|
| average_latency | 0.0427742 |
| average_error   | 0         |

**Comment by harshad16** [comment]
The following table shows gathered metrics on your deployed model.

|   average_latency |   average_error | model_version   |
|------------------:|----------------:|:----------------|
|         0.0378547 |               0 | pr-157          |

**Comment by harshad16** [comment]
The following table shows gathered metrics on your deployed model.

|   average_latency |   average_error | model_version   |
|------------------:|----------------:|:----------------|
|         0.0389021 |               0 | pr-157          |

**Comment by harshad16** [comment]
The following table shows gathered metrics on your deployed model.

|   average_latency |   average_error | model_version   |
|------------------:|----------------:|:----------------|
|         0.0478547 |           0.003 | v0.5.0          |
|         0.0374796 |           0     | pr-157          |

**Comment by goern** [comment]
how many requests are made to calculate the averages? is that something the data scientist can set in the feature file?

**Comment by pacospace** [comment]
> how many requests are made to calculate the averages? is that something the data scientist can set in the feature file?

It depends on the test dataset, for this example with MNIST, 10k requests are done. Yes DS should decide the test dataset, so depending on that they can tune how many requests they want to do

**Comment by harshad16** [comment]
The following table shows gathered metrics on your deployed models.

|   average_latency |   average_error | model_version   |
|------------------:|----------------:|:----------------|
|         0.0382317 |               0 | pr-157          |

**Comment by harshad16** [comment]
The following table shows gathered metrics on your deployed models.

|   average_latency |   average_error | model_version   |
|------------------:|----------------:|:----------------|
|         0.0426968 |               0 | pr-157          |

**Comment by harshad16** [comment]
The following table shows gathered metrics on your deployed models.

|   average_latency |   average_error | model_version   |
|------------------:|----------------:|:----------------|
|         0.0389865 |               0 | pr-157          |

**Comment by harshad16** [comment]
The following table shows gathered metrics on your deployed models.

|   average_latency |   average_error | model_version   |
|------------------:|----------------:|:----------------|
|          0.039965 |               0 | pr-157          |

**Comment by harshad16** [comment]
The following table shows gathered metrics on your deployed models.

|   average_latency |   average_error | model_version   |
|------------------:|----------------:|:----------------|
|         0.0470459 |               0 | pr-157          |

**Comment by harshad16** [comment]
The following table shows gathered metrics on your deployed models.

|   average_latency |   average_error | model_version   |
|------------------:|----------------:|:----------------|
|         0.0407742 |               0 | pr-157          |

**Comment by harshad16** [comment]
The following table shows gathered metrics on your deployed models.

|   average_latency |   average_error | model_version   |
|------------------:|----------------:|:----------------|
|         0.0414944 |               0 | pr-157          |

**Comment by harshad16** [comment]
The following table shows gathered metrics on your deployed models.

|   average_latency |   average_error | model_version   |
|------------------:|----------------:|:----------------|
|         0.0947749 |               0 | pr-157          |

**Comment by harshad16** [comment]
The following table shows gathered metrics on your deployed models.

|   average_latency |   average_error | model_version   |
|------------------:|----------------:|:----------------|
|         0.0440388 |               0 | pr-157          |

**Comment by harshad16** [comment]
The following table shows gathered metrics on your deployed models.

|   average_latency |   average_error | model_version   |
|------------------:|----------------:|:----------------|
|         0.0715836 |               0 | pr-157          |

**Comment by harshad16** [comment]
The following table shows gathered metrics on your deployed models.

|   average_latency |   average_error |   average_probability |   number_requests | model_version   |
|------------------:|----------------:|----------------------:|------------------:|:----------------|
|         0.0488817 |               1 |                     1 |             10000 | pr-157          |

**Comment by harshad16** [comment]
The following table shows gathered metrics on your deployed models.

|   average_latency |   average_error |   average_probability |   number_requests | model_version   |
|------------------:|----------------:|----------------------:|------------------:|:----------------|
|          0.052493 |               0 |                     1 |             10000 | pr-157          |

**Comment by harshad16** [comment]
The following table shows gathered metrics on your deployed models.

|   average_latency |   average_error |   average_probability |   number_requests | model_version   |
|------------------:|----------------:|----------------------:|------------------:|:----------------|
|         0.0476986 |               0 |              0.999836 |                11 | pr-157          |

**Comment by pacospace** [comment]
@harshad16 also here we need to update resources for prow?

**Comment by harshad16** [comment]
> also here we need to update resources for prow?

yes , with the pr: #159

**Comment by harshad16** [comment]
The following table shows gathered metrics on your deployed models.

|   average_latency |   average_error |   average_probability |   number_requests | model_version   |
|------------------:|----------------:|----------------------:|------------------:|:----------------|
|         0.0391719 |               0 |              0.999836 |                11 | pr-157          |

**Comment by harshad16** [comment]
The following table shows gathered metrics on your deployed models.

|   average_latency |   average_error |   average_probability |   number_requests | model_version   |
|------------------:|----------------:|----------------------:|------------------:|:----------------|
|         0.0604327 |               0 |              0.999836 |                11 | pr-157          |

**Pull request merged**
