### PR TITLE
Create flask app with endpoints to request prediction and metrics

### PR DESCRIPTION
**Pull request by pacospace**
Related-To: https://github.com/orgs/thoth-station/projects/15#card-53170823

### CODE REVIEW

**Comment by pacospace** [comment]
@fridex PTAL :)

**Review by fridex — COMMENTED** [review]
I'm not familiar with the context here so cannot judge. The code looks good to me briefly looking at it.

**Comment by pacospace** [comment]
> I'm not familiar with the context here so cannot judge. The code looks good to me briefly looking at it.

Regarding the context: https://github.com/orgs/thoth-station/projects/15#card-53170823

We want to show a simple example, if a DS changes the model and stores it on Github, they can just do a git tag and then all thoth machinery will do the rest.

We can extend this example, adding overlays that create three images later and show Elyra pipeline using images created by Thoth automatically and optimized.

**Comment by fridex** [comment]
> > I'm not familiar with the context here so cannot judge. The code looks good to me briefly looking at it.
> 
> Regarding the context: https://github.com/orgs/thoth-station/projects/15#card-53170823
> 
> We want to show a simple example, if a DS changes the model and stores it on Github, they can just do a git tag and then all thoth machinery will do the rest and redeploy new image with new model.
> 
> We can extend this example, adding overlays that create three images later and show Elyra pipeline using images created by Thoth automatically and optimized.

Is this something we could discuss during tech talks or our demo session? I'm afraid I will not be helpful here with the info I have.

**Comment by pacospace** [comment]
> > > I'm not familiar with the context here so cannot judge. The code looks good to me briefly looking at it.
> > 
> > 
> > Regarding the context: https://github.com/orgs/thoth-station/projects/15#card-53170823
> > We want to show a simple example, if a DS changes the model and stores it on Github, they can just do a git tag and then all thoth machinery will do the rest and redeploy new image with new model.
> > We can extend this example, adding overlays that create three images later and show Elyra pipeline using images created by Thoth automatically and optimized.
> 
> Is this something we could discuss during tech talks or our demo session? I'm afraid I will not be helpful here with the info I have.

Yes sure! and I will update today during scrum :)

**Comment by fridex** [comment]
> Yes sure! and I will update today during scrum :)

Cool, thanks! I went through the linked issues, but it might be better to explain things, also for the whole team.

**Comment by goern** [comment]
/approve
/assign @pacospace 
/sig devops
/sig documentation
/sig user-experience
/kind feature

/ well-done!

**Pull request merged**
